version: '3.8'

services:
  app:
    build: .
    container_name: notification-system
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
      - DB_URI=mongodb://mongo:27017/notification_db
    depends_on:
      - mongo
      - kafka

  mongo:
    image: mongo:latest
    container_name: notification-mongo
    environment:
      MONGO_INITDB_DATABASE: notification_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017" 

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

volumes:
  mongo_data:
    driver: local
